export const appName = 'Predračuni'
export const logRegTitle = 'Ogrevanje Janjić'
export const author = 'Andželko Janjić'
export const place = 'Prosenjakovci'
export const picturesPath = './pictures/'
export const countriesPath = './countries/'
