const general = {
    si: {
        general: {
            edit: 'Uredi',
            copy: 'Kopiraj',
            view: 'Ogled',
            export: 'Izvozi',
            total: 'Promet',
            delete: 'Izbriši',
            helloMessage: 'Pozdravljeni :)',
            deleteMessage: 'Želite izbrisati vnos?',
            deleteALL: 'Želite izbrisati predračun?',
            deleteMessageWarning: 'Izbrisani bodo vsi strankini predračuni in računi!',
            deleteTitle: 'Brisanje',
            wrongEmail: 'Neveljaven email',
            enterPost: 'Vnesite pošto',
            enterCityStreet: 'Vnesite kraj/ulica',
            enterCustomer: 'Vnesite podjetje / ime priimek',
            createCustomer: 'Nova stranka',
            min6: 'Minimalno 6 znakov',
            repeatPassword: 'Ponovite geslo',
            enterPassword: 'Vnesite geslo',
            enterToken: 'Vnesite žeton',
            passMissmatch: 'Gesli se ne ujemata',
            tokenLen20: 'Žeton je dolžine 20 znakov',
            pictureFormats: 'Dovoljeni formati so .jpg, .jpeg, .png',
            choosePicture: 'Izberite sliko',
            enterDescription: 'Vnesite opis',
            descriptionChanged: 'Opis je spremenjen',
            enterEM: 'Izberite EM',
            enterPrice: 'Vnesite ceno',
            enterQty: 'Vnesite količino',
            val0to99: 'Vrednost od 0 do 99',
            enterTitle: 'Vnesite naziv',
            recipientAdded: 'Prejemnik je dodan',
            recipient: 'Prejemnik',
            itemAdded: 'Artikel je dodan',
            enterCustomerInvoice: 'Vnesite stranko',
            chooseExpDate: 'Izberite datum zapadlosti',
            chooseWorkDate: 'Izberite opravljeno dne',
            chooseKlavzula: 'Izberite klavzulo',
            recipientRemoved: 'Prejemnik je odstranjen',
            klavzulaAdded: 'Klavzula je dodana',
            VATadded: 'Davek je dodan',
            expidationDateAdded: 'Datum zapadlosti je dodan',
            workDateAdded: 'Opravljeno dne je dodano',
            customerAdded: 'Stranka je dodana',
            enterEmail: 'Vnesite email',
            enterUsername: 'Vnesite uporabniško ime',
            editRecipient: 'Urejanje prejemnika',
            dateFromTo: 'Datum od je večji od datuma do',
            biggerThan0: 'Mora biti večje od 0',
            EMChanged: 'Enota mere je spremenjena',
            pricePerItemChanged: 'Cena/kos spremenjena',
            discountChanged: 'Popust spremenjen',
            lessThan100prc: 'Mora biti od 0 do 99 %',
            itemRemoved: 'Artikel je odstranjen',
            klavzulaChanged: 'Klavzula je spremenjena',
            VATChanged: 'Davek je spremenjen',
            createdChanged: 'Ustvarjen dne je spremenjen',
            expirationChanged: 'Datum zapadlosti je spremenjen',
            workDateChanged: 'Opravljeno dne je spremenjeno',
            customerChanged: 'Stranka je spremenjena',
            QTYChanged: 'Količina je spremenjena',
            update: 'Osveži',
            settings: 'Nastavitve',
            day: 'dan',
            visitsOnPage: 'Obiskov na strani v obdobju',
            days: 'dni',
            totalPerMonth: 'Promet po mesecih',
            newInsert: 'Nov vnos'
        },
        klavzule: {
            newKlavzula: 'Nova klavzula',
            klavzulaShort: 'Vnesite kratico',
            klavzulaDesc: 'Vnesite Opis',
            editKlavzula: 'Uredi klavzulo'
        },
        customers: {
            editCustomer: 'Uredi stranko',
            newUser: 'Nov uporabnik',
            create: 'Nova stranka',
            report: {
                sifra: 'Šifra',
                timestamp: 'Ustvarjen',
                total: 'Znesek',
                expiration: 'Zapadlost',
                iznosi: 'Izpiši vse iznose',
                predracuni: 'Izdani predračuni',
                racuni: 'Izdani računi'
            }
        },
        employees: {
          editEmployee: 'Uredi zaposlenega',
          insertEmployee: 'Vnesite ime in priimek zaposlenega',
          enterAddress: 'Vnesite naslov',
          createEmployee: 'Nov zaposleni',
          addInsert: 'Nov vnos'
        },
        hours: {
          newMonthlyReport: 'Nov mesečni izpis',
          dayAdded: 'Vnos je dodan',
          dayType: 'Izberite tip dneva',
          chooseDate: 'Izberite datum',
          chooseMonth: 'Izberite mesec',
          chooseEmployee: 'Izberite zaposlenega',
          fullDay: 'Prazno polje se smatra kot cel dan',
          dayRemoved: 'Dan je odstranjen',
          dayTypeChanged: 'Tip dneva spremenjen',
          dateChanged: 'Datum je spremenjen',
          listTotal: 'Izbriši celoten mesečni izpis',
          employee: 'Zaposleni',
          month: 'Mesec',
          monthReportEdit: 'Urejanje mesečnega izpisa',
          hoursMonthReport: 'Evidenca o izrabi delovnega časa za mesec',
          day_type: 'Tip dneva',
          date: 'Datum',
          daysTotal: 'Skupaj dni',
          NU1 : 'bolniška do 30 dni, izredni dopust...',
          NU2: 'bolniška nad 30 dni, krvodajalstvo',
          NU3: 'brez nadomestila plače',
          holiday: 'Letni dopust',
          work_day: 'Delovni dan',
          festival: 'Praznik',
          NU1_text: 'neopravljene ure za katere nadomestilo plača delodajalec-bolniška do 30 dni, izredni dopust…',
          NU2_text: 'neopravljene ure za katere nadomestilo plača druga organiz.-bolniška nad 30 dni, krvodajalstvo…',
          NU3_text: 'neopravljene ure za katere se ne dobi nadomestilo plače',
          NU1_short: 'NU1',
          NU2_short: 'NU2',
          NU3_short: 'NU3'
        },
        statistics: {
            allVisits: 'Vseh obiskov',
            avg: 'Povprečno',
            totalEarnings: 'Promet za obdobje'
        },
        drawer: {
            invoices: 'Predračuni',
            customers: 'Stranke',
            finalInvoices: 'Računi',
            total: 'Promet',
            website: 'Web stran',
            users: 'Uporabniki',
            klavzule: 'Klavzule',
            company: 'Podjetje',
            hours: 'Ure'
        },
        header: {
            user: 'Uporabnik'
        },
        invoices: {
            predracun: 'Ogled predračuna',
            racun: 'Ogled računa',
            iban: 'IBAN',
            swift: 'SWIFT',
            sklicevanje_stev: 'Sklicevanje na štev.',
            invoice: 'Predračun',
            final: 'Račun',
            validity: 'Veljavnost',
            work_done: 'Delo opravljeno',
            id_ddv: 'ID za DDV',
            id_ddv_customer: 'ID za DDV kupca',
            recipient: 'Prejemnik',
            description: 'Opis blaga',
            em: 'EM',
            qty: 'Količina',
            price: 'Cena',
            discount: 'Popust',
            ddv: 'DDV',
            vrednost: 'Vrednost',
            skupaj: 'Skupaj',
            osnova: 'osnova',
            zeroEUR: '0,00 EUR',
            forPayment: 'ZA PLAČILO',
            total76A: 'Skupaj 76.A člen',
            addItem: 'Dodaj artikel',
            klavzula76ATrans: 'VAT is accounted by the place of immovoble property under Article 47 of Directive.'
        },
        report: {
            book: 'KNJIGA IZDANIH RAČUNOV - promet blaga in storitev za obdobje',
            noData: 'Ni dosegljivih podatkov',
            from: 'od',
            to: 'do'
        }
    }
}

export default general
