const general = {
    si: {
        general: {
            edit: 'Uredi',
            copy: 'Kopiraj',
            view: 'Ogled',
            export: 'Izvozi',
            total: 'Promet',
            delete: 'Izbriši',
            helloMessage: 'Pozdravljeni :)',
            deleteMessage: 'Želite izbrisati vnos?',
            deleteALL: 'Želite izbrisati predračun?',
            deleteMessageWarning: 'Izbrisani bodo vsi strankini predračuni in računi!',
            deleteTitle: 'Brisanje',
            wrongEmail: 'Neveljaven email',
            enterPost: 'Vnesite pošto',
            enterCityStreet: 'Vnesite kraj/ulica',
            enterCustomer: 'Vnesite podjetje / ime priimek',
            createCustomer: 'Nova stranka',
            min6: 'Minimalno 6 znakov',
            repeatPassword: 'Ponovite geslo',
            passMissmatch: 'Gesli se ne ujemata',
            pictureFormats: 'Dovoljeni formati so .jpg, .jpeg, .png',
            choosePicture: 'Izberite sliko',
            enterDescription: 'Vnesite opis',
            enterEM: 'Izberite EM',
            enterPrice: 'Vnesite ceno',
            enterQty: 'Vnesite količino',
            val0to99: 'Vrednost od 0 do 99',
            enterTitle: 'Vnesite naziv',
            recipientAdded: 'Prejemnik je dodan',
            recipient: 'Prejemnik',
            itemAdded: 'Artikel je dodan',
            enterCustomerInvoice: 'Vnesite stranko',
            chooseExpDate: 'Izberite datum zapadlosti',
            chooseWorkDate: 'Izberite opravljeno dne',
            chooseKlavzula: 'Izberite klavzulo',
            recipientRemoved: 'Prejemnik je odstranjen',
            klavzulaAdded: 'Klavzula je dodana',
            VATadded: 'Davek je dodan',
            expidationDateAdded: 'Datum zapadlosti je dodan',
            workDateAdded: 'Opravljeno dne je dodano',
            customerAdded: 'Stranka je dodana',
            enterEmail: 'Vnesite email',
            enterUsername: 'Vnesite uporabniško ime',
            editRecipient: 'Urejanje prejemnika',
            dateFromTo: 'Datum od je večji od datuma do',
            biggerThan0: 'Mora biti večje od 0',
            EMChanged: 'Enota mere je spremenjena',
            pricePerItemChanged: 'Cena/kos spremenjena',
            discountChanged: 'Popust spremenjen',
            lessThan100prc: 'Mora biti od 0 do 99 %',
            itemRemoved: 'Artikel je odstranjen',
            klavzulaChanged: 'Klavzula je spremenjena',
            VATChanged: 'Davek je spremenjen',
            createdChanged: 'Ustvarjen dne je spremenjen',
            expirationChanged: 'Datum zapadlosti je spremenjen',
            workDateChanged: 'Opravljeno dne je spremenjeno',
            customerChanged: 'Stranka je spremenjena',
            QTYChanged: 'Količina je spremenjena',
            update: 'Osveži',
            settings: 'Nastavitve',
            day: 'dan',
            visitsOnPage: 'Obiskov na strani v obdobju',
            days: 'dni',
            totalPerMonth: 'Promet po mesecih'
        },
        klavzule: {
            newKlavzula: 'Nova klavzula',
            klavzulaShort: 'Vnesite kratico',
            klavzulaDesc: 'Vnesite Opis',
            editKlavzula: 'Uredi klavzulo'
        },
        customers: {
            editCustomer: 'Uredi stranko',
            newUser: 'Nov uporabnik',
            create: 'Nova stranka',
            report: {
                sifra: 'Šifra',
                timestamp: 'Ustvarjen',
                total: 'Znesek',
                expiration: 'Zapadlost',
                iznosi: 'Izpiši vse iznose',
                predracuni: 'Izdani predračuni',
                racuni: 'Izdani računi'
            }
        },
        statistics: {
            allVisits: 'Vseh obiskov',
            avg: 'Povprečno',
            totalEarnings: 'Promet za obdobje'
        },
        drawer: {
            invoices: 'Predračuni',
            customers: 'Stranke',
            finalInvoices: 'Računi',
            total: 'Promet',
            website: 'Web stran',
            users: 'Uporabniki',
            klavzule: 'Klavzule',
            company: 'Podjetje'
        },
        header: {
            user: 'Uporabnik'
        },
        invoices: {
            predracun: 'Ogled predračuna',
            racun: 'Ogled računa',
            iban: 'IBAN',
            swift: 'SWIFT',
            sklicevanje_stev: 'Sklicevanje na štev.',
            invoice: 'Predračun',
            final: 'Račun',
            validity: 'Veljavnost',
            work_done: 'Delo opravljeno',
            id_ddv: 'ID za DDV',
            id_ddv_customer: 'ID za DDV kupca',
            recipient: 'Prejemnik',
            description: 'Opis blaga',
            em: 'EM',
            qty: 'Količina',
            price: 'Cena',
            discount: 'Popust',
            ddv: 'DDV',
            vrednost: 'Vrednost',
            skupaj: 'Skupaj',
            osnova: 'osnova',
            zeroEUR: '0,00 EUR',
            forPayment: 'ZA PLAČILO',
            total76A: 'Skupaj 76.A člen'
        },
        report: {
            book: 'KNJIGA IZDANIH RAČUNOV - promet blaga in storitev za obdobje',
            noData: 'Ni dosegljivih podatkov',
            from: 'od',
            to: 'do'
        }
    }
}

export default general
